#!/bin/bash
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "ALTERA SENHA ROOT" ; tput sgr0
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
echo -e "\033[1;32m"
read -p "NOVA SENHA : " senha
(echo $senha ; echo $senha) | passwd root 1>/dev/null 2>/dev/null
echo -e "\033[1;32mNova Senha Do Root Foi Salva com Sucesso"
sleep 3
echo " "
echo -e "\033[1;31mNova Senha:\033[1;32m $senha"
sleep 4
sudo vpspack
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpspack
exit
