#!/bin/bash
clear
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
echo -e ""$b"ATUALIZANDO REPOSITORIOS..."
if apt-get update -y 1>/dev/null 2>/dev/null
then
apt-get upgrade -y 1>/dev/null 2>/dev/null
echo ""
echo -e ""$v"Sucesso! "$b"REPOSITORIOS ATUALIZADOS COM SUCESSO.."
else
yum -y update 1>/dev/null 2>/dev/null
yum -y upgrade 1>/dev/null 2>/dev/null
echo ""
echo -e ""$v"Sucesso! "$b"REPOSITORIOS ATUALIZADOS COM SUCESSO.."
sleep 2
fi
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU PRINCIPAL..."
read ENTER
vpspack
exit
