#!/bin/bash

BACKUPS="/home/DATABASE/Backups"

clear
echo -e "\033[01;36mLista de backups criados:\033[01;32m 0: RETORNAR AO MENU."
echo ""
NUMBER=$(ls $BACKUPS | wc -l)
if [ $NUMBER = "0" ]; then
  echo -e "\033[01;33mVocê não possui nenhum backup criado no momento!"
  echo ""
  echo -e "\033[01;33mPara prosseguir com esta opção será necessário criar um backup!"
  echo ""
  echo -e "\033[01;36mAPERTE A TECLA ENTER PARA VOLTAR AO MENU..."
  read ENTER
  backupsmanager-menu
  exit
else
  for BACKUP in `ls $BACKUPS | sort | sed "s/.zip//g"`; do
    echo -ne "\033[01;33m"; echo $BACKUP
  done
fi
echo ""
echo -ne "\033[01;36mDigite o nome do backup:\033[01;37m "; read NAME
if [ -z $NAME ]; then
  echo ""
  echo -e "\033[01;37;41mVocê digitou um nome de backup vazio. Tente novamente!\033[0m"
  sleep 3s
  backupsmanager-import
  exit
else
if [ "$NAME" = "0" ]; then
  backupsmanager-menu
  exit
else
if [[ `ls $BACKUPS | grep -cx "$NAME.zip"` -ne 1 ]]; then
  echo ""
  echo -e "\033[01;37;41mVocê digitou um nome de backup inexistente. Digite um nome de\033[0m"; echo -e "\033[01;37;41mbackup que seja existente na lista acima. Tente novamente!   \033[0m"
  sleep 7s
  backupsmanager-import
  exit
else
  echo ""
  echo -e "\033[01;37mAguarde..."
  sleep 3s
  cp $BACKUPS/$NAME.zip /
  cd /
  tar -xvf $NAME.zip 1> /dev/null 2> /dev/null
  rm -rf $NAME.zip
  clear
  echo -e "\033[01;36mLista de backups criados:"; echo ""
  for BACKUP in `ls $BACKUPS | sort | sed "s/.zip//g"`; do
    echo -ne "\033[01;33m"; echo $BACKUP
  done
  echo ""
  echo -e "\033[01;32mBackup importado com sucesso! Verifique as informações abaixo:"
  echo ""
  echo -e "\033[01;32mNome do backup: $NAME"
  echo ""
  echo -e "\033[01;32mForam importados:"
  echo ""
  echo -e "\033[01;37m→ Backup completo de usuários SSH."
  echo -e "\033[01;37m→ Backup completo do banco de dados do ADM VPS."
  echo -e "\033[01;37m→ Senha de usuário ROOT."
fi
fi
fi
echo ""
echo -ne "\033[01;36mAPERTE A TECLA ENTER..."
read ENTER
vpn
exit
