#!/bin/bash
clear

echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e " \033[7;30;46m\033[5;37;40m                   VPN DROPBEAR                    \033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"

# cores
b="\033[1;37m"
v="\033[1;32m"
ama="\033[1;33m"
Ver="\033[1;31m"
az="\033[1;36m"
#
if cat /etc/shells |grep "/bin/false" >/dev/null; then
echo -n
else
echo "/bin/false" >>/etc/shells
fi

echo '' 
echo -e '\033[01;33m  •\033[01;32m DIGITE A PORTA PARA USAR NO Dropbear.'
echo -ne '\033[01;33m  •\033[01;33m PORTA: ';read porta
if [[ -z "$porta" ]]; then
  echo -e "\033[1;37m   Porta invalida!"
  sleep 1.5
  echo -e "Saindo..."
  sleep 1.5
  exit 69
fi
if [[ "$porta" = '80' ]]; then
 if [[ -d /etc/squid3 ]]; then
	if cat /etc/squid3/squid.conf | grep 80 1> /dev/null 2> /dev/null ; then
		echo ''
		echo -e "$Ver"'    Porta'"$ama"' 80' "$Ver"'esta ativa no squid3'
		echo ''
		echo -e "\033[01;33m  •\033[01;31m PARA CONTINUAR COM A INSTALAÇÃO DO Dropbear NA PORTA"$ama" 80 "$Ver"TERA QUE REMOVER ELA DO SQUID3"
		sleep 0.5
		echo ''
		echo -ne "\033[1;33m    CONTINUAR? \033[01;32m s/n\033[1;37m:"; read re
		if [[ "$re" = 's' ]]; then
              
              sleep  1
              echo ''
              echo -e "\033[01;33m  •\033[01;32m REMOVENDO PORTA DO SQUID3..."
              p=$(cat /etc/squid3/squid.conf | sed s/"http_port 80"/"# http_port 80"/|grep -v "# http_port 8080" |sed s/"# http_port 80"/"http_port 8080"/)
              echo "$p" > /etc/squid3/squid.conf
              service squid3 restart 1>/dev/null 2>/dev/null
              sleep 1
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo ''
              echo -e "\033[01;33m  •\033[01;32m INSTALANDO DROPBEAR..."
              apt-get update 1>/dev/null 2>/dev/null
              apt-get install dropbear -y 1>/dev/null 2>/dev/null
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              sleep 1
              echo ''
              echo -e "\033[01;33m  •\033[01;32m ADICIONANDO PORTA..."
              echo "NO_START=0" > /etc/default/dropbear
              echo "DROPBEAR_PORT=80" >> /etc/default/dropbear
              sleep 1
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo ''
              echo -e "\033[01;33m  •\033[01;32m REINICIANDO DROPBEAR..."
              service dropbear start 1>/dev/null 2>/dev/null
              service dropbear restart 1>/dev/null 2>/dev/null
              sleep 1
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo ''
              echo -e "\033[01;33m  •\033[01;33m INSTALAÇÃO FINALIZADA COM SUCESSO.\033[0m"
              exit 69
              echo ''
              echo ''
              echo ''
    fi 
    if [[ "$re" = 'n' ]]; then
               echo -e ""$Ver"Saindo..."
               sleep 3s
               vpn
               exit
    fi
    fi
 else
 true
 fi
 if [[ -d /etc/squid ]]; then
  if cat /etc/squid/squid.conf | grep 80 1> /dev/null 2> /dev/null ; then
		echo -e "$Ver"'   Porta 80 esta ativa no squid'
		echo ''
		echo -e "$b""PARA CONTINUAR COM A INSTALAÇÃO DO Dropbear NA\nPORTA 80 TERA QUE REMOVER ELA DO SQUID"
		sleep 0.5
		echo ''
		echo -ne "\033[1;33m    CONTINUAR? \033[01;32m s/n\033[1;37m:"; read rees
		if [[ "$rees" = 's' ]]; then
              echo -e "$v""Continuando..."
              sleep  1
              echo ''
              echo -e "\033[01;33m  •\033[01;32m REMOVENDO PORTA DO SQUID..."
              p=$(cat /etc/squid/squid.conf | sed s/"http_port 80"/"# http_port 80"/|grep -v "# http_port 8080" |sed s/"# http_port 80"/"http_port 8080"/)
              echo "$p" > /etc/squid/squid.conf
              service squid3 restart 1>/dev/null 2>/dev/null
              sleep 1
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo -e "\033[01;33m  •\033[01;32m INSTALANDO DROPBEAR..."
              apt-get update 1>/dev/null 2>/dev/null
              apt-get install dropbear -y 1>/dev/null 2>/dev/null
              sleep 1
              echo ''
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo -e "\033[01;33m  •\033[01;32m ADICIONANDO PORTA..."
              echo "NO_START=0" > /etc/default/dropbear
              echo "DROPBEAR_PORT=80" >> /etc/default/dropbear
              sleep 1
              echo ''
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo -e "\033[01;33m  •\033[01;32m REINICIANDO DROPBEAR..."
              service dropbear start 1>/dev/null 2>/dev/null
              service dropbear restart 1>/dev/null 2>/dev/null
              sleep 1
              echo ''
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo ''
              echo -e "\033[01;33m  •\033[01;33m INSTALAÇÃO FINALIZADA COM SUCESSO.\033[0m"
              inter=$(cat /bin/CONFVPS3 | sed 's;INSTALAR DROPBEAR ;GERENCIAR DROPBEAR;')
	      echo "$inter" > /bin/CONFVPS3
              exit 69
    fi
    if [[ "$rees" = 'n' ]]; then
               echo -e ""$Ver"Saindo..."
               sleep 3s
               vpn
               exit
    fi
    fi
fi
 else
 true
 fi
if [[ "$porta" = '443' ]]; then
  if cat /etc/ssh/sshd_config |grep "443" >/dev/null; then
    echo -e ""$Ver"Porta 443 esta adicionada no sshd!"
    echo ''
    echo -e "$b""PARA CONTINUAR COM A INSTALAÇÃO DO Dropbear NA\nPORTA 443 TERA QUE REMOVER ELA DO SSHD"
    echo ''
    echo -ne "\033[1;33m    CONTINUAR? \033[01;32m s/n\033[1;37m:"; read ss
      if [[ "$ss" = 's' ]]; then
      	echo -e "$v""Continuando..."
      	echo ''
      	echo -e "\033[01;33m  •\033[01;32m REMOVENDO PORTA DO SSHD..."
      	port=$(cat /etc/ssh/sshd_config | grep -v "Port 443")
        echo "$port" > /etc/ssh/sshd_config
        sleep 1
        echo ''
        echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
        echo -e "\033[01;33m  •\033[01;32m REINICIANDO SSH..."
        service ssh restart >/dev/null 2>/dev/null
        sleep 1
        echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
        echo -e "\033[01;33m  •\033[01;32m INSTALANDO DROPBEAR..."
        apt-get update 1>/dev/null 2>/dev/null
        apt-get install dropbear -y 1>/dev/null 2>/dev/null
        sleep 1
        echo ''
        echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
        echo -e "\033[01;33m  •\033[01;32m ADICIONANDO PORTA..."
echo "NO_START=0" > /etc/default/dropbear
echo "DROPBEAR_PORT=443" >> /etc/default/dropbear
        sleep 1
        echo ''
        echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
        echo -e "\033[01;33m  •\033[01;32m REINICIANDO DROPBEAR..."
        service dropbear restart 1>/dev/null 2>/dev/null
        sleep 1
        echo ''
        echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
        echo ''
        echo -e "\033[01;33m  •\033[01;33m INSTALAÇÃO FINALIZADA COM SUCESSO.\033[0m"
        exit 69
        inter=$(cat /bin/CONFVPS3 | sed 's;INSTALAR DROPBEAR ;GERENCIAR DROPBEAR;')
        echo "$inter" > /bin/CONFVPS3
    else
    	echo -e -n ""
    fi
    if [[ "$ss" = 'n' ]]; then
    	echo -e ""$Ver"Saindo..."
               sleep 3s
               vpn
               exit
    fi
fi
fi
 echo -e "\033[01;33m  •\033[01;32m INSTALANDO DROPBEAR..."
              apt-get update 1>/dev/null 2>/dev/null
              apt-get install dropbear -y 1>/dev/null 2>/dev/null
              sleep 1
              echo ''
              echo -e ""$b"   ["$ama"OK"$b"]$az Sucesso..."
              echo -e "\033[01;33m  •\033[01;32m ADICIONANDO PORTA..."
              echo "NO_START=0" > /etc/default/dropbear
              echo "DROPBEAR_PORT=$porta" >> /etc/default/dropbear
              sleep 1
              echo ''
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo -e "\033[01;33m  •\033[01;32m REINICIANDO DROPBEAR..."
              service dropbear start 1>/dev/null 2>/dev/null
              service dropbear restart 1>/dev/null 2>/dev/null
              sleep 1
              echo ''
              echo -e ""$b"    ["$ama"OK"$b"]$az Sucesso..."
              echo ''
              echo -e "\033[01;33m  •\033[01;33m INSTALAÇÃO FINALIZADA COM SUCESSO.\033[0m"
              echo ''
              echo ''
              echo ''
