#!/bin/bash
###cores
verm="\033[1;31m"
verd="\033[1;32m"
ama="\033[1;33m"
azu="\033[1;34m"
fi="\033[0m"
###cores
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "ADICIONAR HOSTS EM (etc/hosts)&(etc/payloads)" ; tput sgr0
echo ""
echo "        Created @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear

ip=127.0.0.1
echo ""
echo -e "\033[0;31;40m    •\033[0m\033[0;36;40m  Qual\033[0m \033[7;30;41mHOST\033[0m\033[0m \033[0;36;40mdeseja adicionar?\033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"
read -p ": " host
echo "$ip $host" >> /etc/hosts
echo "$host" >> /etc/payloads

chmod a+x /etc/hosts
clear
				if [ ! -f "/etc/init.d/squid" ]
				then
					service squid3 reload
            service squid3 restart
				else
					/etc/init.d/squid reload
            service squid restart
				fi	
echo -e "$azu"
echo "O Proxy Squid foi recarregado com sucesso e as hosts adicionadas!"
echo -e "$fi"
 echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpspack
exit
