#!/bin/bash

ip=$(wget -qO- ipv4.icanhazip.com)
clear
if [[ $1 == "" ]]
then
dia=$(date | awk {'print $3'})
mes=$(date | awk {'print $2'})
ano=$(date | awk {'print $6'})
if [[ "$mes" = "Jan" || "$mes" = "Jan" ]]; then
mes=01
elif [[ "$mes" = "Feb" || "$mes" = "Fev" ]]; then
mes=02
elif [[ "$mes" = "Mar" || "$mes" = "Mar" ]]; then
mes=03
elif [[ "$mes" = "Apr" || "$mes" = "Abr" ]]; then
mes=04
elif [[ "$mes" = "May" || "$mes" = "Mai" ]]; then
mes=05
elif [[ "$mes" = "Jun" || "$mes" = "Jun" ]]; then
mes=06
elif [[ "$mes" = "Jul" || "$mes" = "Jul" ]]; then
mes=07
elif [[ "$mes" = "Ago" || "$mes" = "Ago" ]]; then
mes=08
elif [[ "$mes" = "Set" || "$mes" = "Sep" ]]; then
mes=09
elif [[ "$mes" = "Out" || "$mes" = "Oct" ]]; then
mes=10
elif [[ "$mes" = "Nov" || "$mes" = "Nov" ]]; then
mes=11
elif [[ "$mes" = "Dec" || "$mes" = "Dez" ]]; then
mes=12
fi
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[7;30;47m  DATA:\033[0m\033[7;30;41m $dia/$mes/$ano\033[0m"
echo -e "\033[7;30;47m  IP da VPS:\033[0m\033[7;30;41m $ip\033[0m"
system=$(cat /etc/issue.net)
if [ "$system" ]
then
echo -e "\033[7;30;47m  Sistema Operacional:\033[0m\033[7;30;41m $system\033[0m"
else
echo -e "\033[7;30;47m  Sistema Operacional:\033[0m\033[7;30;41mNot Available\033[0m"
fi
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[7;30;47m  ®Script\033[0m \033[7;30;41mEdited:\033[0m \033[0m \033[0;36;40m@Colt\033[5;37;40mSeals\033[0m"
echo -e "\033[7;30;47m  ®TELEGRAM\033[0m \033[7;30;41mCANAL:\033[0m \033[0m \033[0;36;40m@Vps\033[5;37;40mNerdologia\033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[7;30;46m  Para Acessar o menu Principal:\033[5;37;40m VPN \033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[7;30;46m  Para Acessar este menu digite:\033[5;37;40m Ferramentas \033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[01;36m║\033[1;37m00\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m VOLTAR \033[0;31;40m=\033[0m \033[7;36;40m Voltar ao Menu Principal \033[0m"
echo -e "\033[01;36m║\033[1;37m01\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m BADVPN START \033[0;31;40m=\033[0m \033[7;36;40m Iniciar Badvpn \033[0m"
echo -e "\033[01;36m║\033[1;37m02\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m BADVPN STOP \033[0;31;40m=\033[0m \033[7;36;40m Parar Badvpn \033[0m"
echo -e "\033[01;36m║\033[1;37m03\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m SPEED TEST \033[0;31;40m=\033[0m \033[7;36;40m Teste de conexão velocidade de banda \033[0m"
echo -e "\033[01;36m║\033[1;37m04\033[1;36m║\033[0;31;40m•\033[0m\033[0;31;40m SAIR \033[0;31;40m=\033[0m \033[1;30;41m Sair do Menu VPN. \033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[0;31;40m    •\033[0m\033[01;37m Digite uma Opção:\033[0;37m"; read -p " " opcao
else
opcao=$1
fi
case $opcao in
  0 | 00 )
   vpn;;
  1 | 01 )
  clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "INICIAR BADVPN" ; tput sgr0
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
echo "Antes de CONTINUAR verifique se foi Instalado no Menu INSTALAÇÃO"
echo ""
read -p "De enter para continuar..."
clear
   badvpn start
     echo ""
  echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
  read ENTER
  vpspack
  exit;;
  2 | 02 )
    clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "PARAR BADVPN" ; tput sgr0
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
echo "Antes de CONTINUAR verifique se foi Instalado no Menu INSTALAÇÃO"
echo ""
read -p "De enter para continuar..."
clear
   badvpn stop
     echo ""
  echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
  read ENTER
  vpspack
  exit;;
  3 | 03 )
  clear
  speedtest.py --share
  echo ""
  echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
  read ENTER
  vpspack
  exit;;
  4 | 04 )
   exit;;
   *) gerenciarferramentas;;
esac
