#!/bin/bash
function CTRL() 
{
vpn
exit
}
trap CTRL SIGINT

function AlterarTempo ()
{
tmp1=$1
tmp2=$(date '+%H:%M%S')
var11=$(echo $tmp1 | cut -c 1-2)
var12=$(echo $tmp1 | cut -c 4-5)
var13=$(echo $tmp1 | cut -c 7-8)
var21=$(echo $tmp2 | cut -c 1-2)
var22=$(echo $tmp2 | cut -c 4-5)
var23=$(echo $tmp2 | cut -c 7-8)
calc1=$(echo $var11*3600 + $var12*60 + $var13 | bc)
calc2=$(echo $var21*3600 + $var22*60 + $var23 | bc)
seg=$(($calc2 - $calc1))
min=$(($seg/60))
seg=$(($seg-$min*60))
hor=$(($min/60))
min=$(($min-$hor*60))
hora=$(printf "%02dh:%02dm:%02ds\n" $hor $min $seg;)
echo $hora
}
clear
while :; do
   echo -e "\033[7;30;46m  --------------------------------------------------------------\033[0m"
   echo -e "  \033[0;30;46m                         MONITOR SSH                          \033[0m"
   echo -e "  \033[01;37;44m USUARIOS      RECEBIDO | ENVIADO   TEMPO CONECTADO    STATUS \033[0m"
   echo -e "\033[7;30;46m  --------------------------------------------------------------\033[0m"
while read linha; do
if [[ $linha == *,* ]]; then
IFS=',' read -ra dados <<< "$linha"
if [[ ${dados[1]} =~ \.[0-9]{1,3}:[0-9] ]]; then
_Recebido=$((dados[2] / 2**20))
_Enviados=$((dados[3] / 2**20))
_Data=$(AlterarTempo $(echo -e ${dados[4]} | awk -F' ' '{print $4}'))
   echo -ne " \033[01;33m"; printf '%-21s%-16s%-7s%s' "  ${dados[0]}" "${_Recebido}MB | ${_Enviados}MB " " $_Data"; echo -e "  \033[01;32m     ONLINE" 
    echo -e "\033[7;30;46m  --------------------------------------------------------------\033[0m"
fi
fi
done <<< "$(cat /etc/openvpn/ope*.log | grep -E '\.[0-9]{1,3}:[0-9]')"
  echo ""
  echo -e "\033[01;36m APERTE CTRL+C PARA VOLTAR AO MENU..."

sleep 7s
clear
done
