#!/bin/bash
###cores
verm="\033[1;31m"
verd="\033[1;32m"
ama="\033[1;33m"
azu="\033[1;34m"
fi="\033[0m"
###cores
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "REMOVER HOST DO SQUID" ; tput sgr0
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
payload="/etc/payloads"
echo -e "$verm"
echo "Remover Host do Squid3"
if [ ! -f "$payload" ]
then
	echo "Arquivo $payload não encontrado" 
	exit 1
else
	echo "Domínios atuais no arquivo $payload:" 
echo -e "$verd"
echo "-----------------------------------------"
cat $payload 
echo "-----------------------------------------"
echo -e "$ama"
	read -p "Digite o domínio que deseja remover da lista: " host
	if [[ -z $host ]]
		then
echo "Você digitou um domínio vazio ou não existente!"
			exit 1
		else
		if [[ `grep -c "^$host" $payload` -ne 1 ]]
		then
			echo "O domínio $host não foi encontrado no arquivo $payload"
			exit 1
		else
			grep -v "^$host" $payload > /tmp/a && mv /tmp/a $payload
			echo "Arquivo $payload atualizado, o domínio foi removido com sucesso:" 
echo -e "$verd"
echo "-----------------------------------------"
cat $payload 
echo "-----------------------------------------"
echo -e "$ama"
			if [ ! -f "/etc/init.d/squid" ]
				then
					service squid3 reload
            service squid3 restart
				else
					/etc/init.d/squid reload
            service squid restart
			fi	
echo -e "$azu"
echo "O Proxy Squid3 foi recarregado com sucesso!"
echo -e "$fi"
        sleep 1s       
			exit 1
		fi
	fi
fi
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpspack
exit
