#!/bin/bash
ip=$(wget -qO- ipv4.icanhazip.com)
if [ $(id -u) -eq 0 ]
then
clear
else
echo -e "Execute o script como usuario \033[1;32mroot\033[0m"
exit
fi
if [ -d /etc/VpsPackdir ]
then
true
else
mkdir /etc/VpsPackdir
fi
if [ -d /etc/VpsPackdir/senha ]
then
true
else
mkdir /etc/VpsPackdir/senha
fi
if [ -d /etc/VpsPackdir/limite ]
then
true
else
mkdir /etc/VpsPackdir/limite
fi

clear
if [[ $1 == "" ]]
then
clear
dia=$(date | awk {'print $3'})
mes=$(date | awk {'print $2'})
ano=$(date | awk {'print $6'})
if [[ "$mes" = "Jan" || "$mes" = "Jan" ]]; then
mes=01
elif [[ "$mes" = "Feb" || "$mes" = "Fev" ]]; then
mes=02
elif [[ "$mes" = "Mar" || "$mes" = "Mar" ]]; then
mes=03
elif [[ "$mes" = "Apr" || "$mes" = "Abr" ]]; then
mes=04
elif [[ "$mes" = "May" || "$mes" = "Mai" ]]; then
mes=05
elif [[ "$mes" = "Jun" || "$mes" = "Jun" ]]; then
mes=06
elif [[ "$mes" = "Jul" || "$mes" = "Jul" ]]; then
mes=07
elif [[ "$mes" = "Ago" || "$mes" = "Ago" ]]; then
mes=08
elif [[ "$mes" = "Set" || "$mes" = "Sep" ]]; then
mes=09
elif [[ "$mes" = "Out" || "$mes" = "Oct" ]]; then
mes=10
elif [[ "$mes" = "Nov" || "$mes" = "Nov" ]]; then
mes=11
elif [[ "$mes" = "Dec" || "$mes" = "Dez" ]]; then
mes=12
fi
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[7;30;47m  DATA:\033[0m\033[7;30;41m $dia/$mes/$ano\033[0m"
echo -e "\033[7;30;47m  IP da VPS:\033[0m\033[7;30;41m $ip\033[0m"
system=$(cat /etc/issue.net)
if [ "$system" ]
then
echo -e "\033[7;30;47m  Sistema Operacional:\033[0m\033[7;30;41m $system\033[0m"
else
echo -e "\033[7;30;47m  Sistema Operacional:\033[0m\033[7;30;41mNot Available\033[0m"
fi
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[7;30;47m  ®Script\033[0m \033[7;30;41mEdited:\033[0m \033[0m \033[0;36;40m@Colt\033[5;37;40mSeals\033[0m"
echo -e "\033[7;30;47m  ®TELEGRAM\033[0m \033[7;30;41mCANAL:\033[0m \033[0m \033[0;36;40m@Vps\033[5;37;40mNerdologia\033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[7;30;46m  Para Acessar este menu digite:\033[5;37;40m VPN \033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"

echo -e "\033[01;36m║\033[1;37m00\033[1;36m║\033[0;31;40m•\033[0m\033[0;31;40m SAIR \033[0;31;40m=\033[0m \033[1;30;41m Sair do Menu VPN. \033[0m"
echo -e "\033[01;36m║\033[1;37m01\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m GERENCIAR USUÁRIOS \033[0;31;40m=\033[0m \033[7;36;40m Criar usuários, redefinir etc \033[0m"
echo -e "\033[01;36m║\033[1;37m02\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m GERENCIAR FERRAMENTAS \033[0;31;40m=\033[0m \033[7;36;40m Teste Velocidade, backup etc \033[0m"
echo -e "\033[01;36m║\033[1;37m03\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m GERENCIAR BACKUP \033[0;31;40m=\033[0m \033[7;36;40m Criar backups, importar etc \033[0m"
echo -e "\033[01;36m║\033[1;37m04\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m GERENCIAR PROXΥ SQUID \033[0;31;40m=\033[0m \033[7;36;40m Add hosts,excluir hosts etc \033[0m"
echo -e "\033[01;36m║\033[1;37m05\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m GERENCIAR SISTEMA \033[0;31;40m=\033[0m \033[7;36;40m Atualizar, Limpar cache etc \033[0m"
echo -e "\033[01;36m║\033[1;37m06\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m MENU INSTALAÇÃO \033[0;31;40m=\033[0m \033[7;36;40m Instalações Opcionais \033[0m"
echo -e "\033[01;36m║\033[1;37m07\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m LIMITADOR DE CONEXÕES \033[0;31;40m=\033[0m \033[7;36;40m Limitador \033[0m\033[5;30;42m RECOMENDADO \033[0m"
echo -e "\033[01;36m║\033[1;37m08\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m SOBRE O SCRIPT \033[0;31;40m=\033[0m \033[7;36;40m Informações sobre Desenvolvedor \033[0m"
echo -e "\033[01;36m║\033[1;37m09\033[1;36m║\033[0;31;40m•\033[0m\033[01;37m MAIS OPÇÕES \033[0;31;40m=\033[0m \033[7;36;40m Menus openvpn, Socks etc \033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[0;31;40m    •\033[0m\033[01;37m Digite uma Opção:\033[0;37m"; read -p " " opcao
else
opcao=$1
fi
case $opcao in
  0 | 00 )
   exit;;
  1 | 01 )
   gerenciarusuarios;;
  2 | 02 )
   gerenciarferramentas;;
  3 | 03 )
   gerenciarbackup;;
  4 | 04 )
   gerenciarsquid;;
  5 | 05 )
   gerenciarsistema;;
  6 | 06 )
   menuinstalacao;;
  7 | 07 )
   limiter-menu;;
  8 | 08 )
   sobre;;
  9 | 09 )
   mais;;
   *) vpn;;
esac
